name: Build Installer
on: push
jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -p:PublishProfile=FolderProfile.pubxml ImgTagFanOut\ImgTagFanOut.csproj

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.0.0
        with:
          path: setupScript.iss
          options: /O+

      - uses: actions/upload-artifact@v3
        with:
          name: Setup
          path: InstallerOutput/